baseURL = 'https://tranhuutai2273.github.io/22DTHE7_TaiTH_Profile/'
languageCode = 'vi'
defaultContentLanguage = 'vi'
title = 'Trần Hữu Tài'
theme = 'techblog'
publishDir = 'docs'

[languages.vi]
  languageName = 'Tiếng Việt'
  [languages.vi.params]
    dateFormat = '2 January 2006'

[params]
  subtitle = 'Chia sẻ kiến thức về lập trình mạng'
  description = 'Blog cá nhân chia sẻ về lập trình Java và JavaScript'
  heroTitle = 'Chào mừng đến với Blog của tôi'
  heroSubtitle = 'Chia sẻ kiến thức về Java & JavaScript'
  
  [params.social]
    github = 'https://github.com/TranHuuTai2273'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
    
  [[menu.main]]
    identifier = 'blog'
    name = 'Blog'
    url = '/blog/'
    weight = 2
    
  [[menu.main]]
    identifier = 'about'
    name = 'Về tôi'
    url = '/about/'
    weight = 3

[taxonomies]
  tag = 'tags'
  category = 'categories'

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = true
    lineNumbersInTable = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
